version: 2
jobs:
  build:
    macos:
      - xcode: 10.2.1

    steps:
      - checkout

      - run:
          name: Set up config
          command: source ./scripts/config_update_formula.sh

      - run:
          name: Test new formula
          command: source ./scripts/test_release_formula.sh

      - run:
          name: Upgrade formula
          command: source ./scripts/upgrade_formula.sh
      
      - deploy:
          name: Trigger github release
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "kernlee23@gmail.com"
            git config user.name "kernleee"
            git add .
            git commit -m "Update via CircleCI [ci skip]"
            # Push quietly to prevent showing the token in log
            git push -u origin master
